### ISSUE TITLE
启动 Startup 报异常

### ISSUE THREAD

**Issue by Corybyte** [Corybyte/openrocket#1]
```
java.lang.reflect.InaccessibleObjectException: Unable to make final void javax.swing.JRootPane.setUseTrueDoubleBuffering(boolean) accessible: module java.desktop does not "opens javax.swing" to unnamed module @35f2d947
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at com.github.weisj.darklaf.ui.DarkPopupFactory.setupDoubleBuffering(DarkPopupFactory.java:201)
	at com.github.weisj.darklaf.ui.DarkPopupFactory.setupWindowBackground(DarkPopupFactory.java:167)
	at com.github.weisj.darklaf.ui.DarkPopupFactory.setupHeavyWeightWindow(DarkPopupFactory.java:143)
	at com.github.weisj.darklaf.ui.DarkPopupFactory.setupPopup(DarkPopupFactory.java:125)
	at com.github.weisj.darklaf.ui.DarkPopupFactory.getPopup(DarkPopupFactory.java:64)
	at java.desktop/javax.swing.ToolTipManager.showTipWindow(ToolTipManager.java:350)
	at java.desktop/javax.swing.ToolTipManager$insideTimerAction.actionPerformed(ToolTipManager.java:699)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:311)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:243)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**Comment by Corybyte** [comment]
近期未复现此类问题
